all:
	./makeclean.sh

clean:
	./makeclean.sh clean

distclean:
	./makeclean.sh distclean

gitclean:
	./makeclean.sh gitclean

help:
	@echo make
	@echo make clean
	@echo make distclean
	@echo make gitclean
	@echo make install

install:
	./makeclean.sh install
