all:
	./makewrapper.sh

clean:
	./makewrapper.sh clean

distclean:
	./makewrapper.sh distclean

gitclean:
	./makewrapper.sh gitclean

help:
	@echo make
	@echo make clean
	@echo make distclean
	@echo make gitclean
	@echo make install

install:
	./makewrapper.sh install
